export const SITE = {
  website: "https://stoneyang.top/",
  author: "stoneyang",
  profile: "https://stoneyang.top/",
  desc: "AI 时代零到一验证玩家 · 一人公司 · AI × 阅读 × 结构化思维",
  title: "stoneyang",
  ogImage: "astropaper-og.jpg",
  lightAndDarkMode: true,
  postPerIndex: 4,
  postPerPage: 6,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: false,
  showBackButton: true,
  editPost: {
    enabled: false,
    text: "Edit page",
    url: "https://github.com/stoneyang0213/stoneyang-top/edit/main/",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "zh-CN",
  timezone: "Asia/Shanghai",
} as const;
