export const SITE = {
  website: "https://stoneyang.top/",
  author: "stone杨",
  profile: "https://stoneyang.top/",
  desc: "超级个体 OS · stone杨 · 零到一验证手记 · 一个人 × 一群 Agent,用 meta 思维重造一人公司",
  title: "超级个体 OS",
  ogImage: "astropaper-og.jpg",
  lightAndDarkMode: true,
  postPerIndex: 4,
  postPerPage: 6,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: false,
  showBackButton: true,
  editPost: {
    enabled: false,
    text: "Edit page",
    url: "https://github.com/stoneyang0213/stoneyang-top/edit/main/",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "zh-CN",
  timezone: "Asia/Shanghai",
} as const;
